services:

  mariadb:
    container_name: mariadb
    image: mariadb:11
    ports:
      - "3306:3306"
    environment:
      - MARIADB_DATABASE=${DATABASE_NAME}
      - MARIADB_USER=${DATASOURCE_USER}
      - MARIADB_PASSWORD=${DATASOURCE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATASOURCE_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - fastapi-archetype-net

  fastapi-archetype:
    build:
      context: ${FASTAPI_ARCHETYPE_CONTEXT_PATH}
      dockerfile: ${FASTAPI_ARCHETYPE_DOCKERFILE_PATH}
    container_name: fastapi-archetype
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    environment:
      - DB_DRIVER=${DB_DRIVER}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - APP_NAME=${APP_NAME}
      - LOG_LEVEL=${LOG_LEVEL}
      - OTEL_EXPORT_ENABLED=${OTEL_EXPORT_ENABLED}
      - OTEL_EXPORTER_ENDPOINT=${OTEL_EXPORTER_ENDPOINT}
    networks:
      - fastapi-archetype-net
    depends_on:
      mariadb:
        condition: service_healthy

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_SERVER_HTTP_PORT: 3001
    networks:
      - fastapi-archetype-net
    ports:
      - "3001:3001"
    volumes:
      - ./observability/grafana/storage:/var/lib/grafana
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    networks:
      - fastapi-archetype-net
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  otel-collector:
    image: ${OTELCOL_IMG}
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./observability/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"
      - "8888:8888"
      - "8889:8889"
      - "13133:13133"
      - "4317:4317"
      - "4318:4318"
      - "55679:55679"
    networks:
      - fastapi-archetype-net
    depends_on:
      - jaeger-all-in-one

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./observability/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - fastapi-archetype-net

networks:
  fastapi-archetype-net:

volumes:
  mariadb-data:
